import {
  MOCK_JEV_MODEL,
  SHORT_TERM_LAB_VERSION,
  STRATEGIES,
  type ShortTermAnalysisRequest,
  type ShortTermAnalysisResult,
  type StrategyId,
} from "@/lib/short-term/types";

const TICKER_PATTERN = /^[A-Z][A-Z0-9.-]{0,9}$/;

function isStrategyId(value: unknown): value is StrategyId {
  return typeof value === "string" && value in STRATEGIES;
}

function finiteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

export function normalizeShortTermRequest(input: unknown): ShortTermAnalysisRequest {
  if (!input || typeof input !== "object") throw new Error("Request body is required");
  const body = input as Record<string, unknown>;
  const ticker = typeof body.ticker === "string" ? body.ticker.trim().toUpperCase() : "";
  if (!TICKER_PATTERN.test(ticker)) {
    throw new Error("Ticker must be 1-10 characters using letters, digits, '.' or '-'");
  }
  if (!isStrategyId(body.strategyId)) throw new Error("Strategy is invalid");
  if (!finiteNumber(body.horizonHours) || !Number.isInteger(body.horizonHours) || body.horizonHours < 1 || body.horizonHours > 48) {
    throw new Error("Horizon must be an integer from 1 to 48 hours");
  }
  if (!finiteNumber(body.maxLossPct) || body.maxLossPct <= 0 || body.maxLossPct > 10) {
    throw new Error("Maximum loss must be greater than 0 and no more than 10 percent");
  }
  return {
    ticker,
    strategyId: body.strategyId,
    horizonHours: body.horizonHours,
    maxLossPct: Math.round(body.maxLossPct * 100) / 100,
  };
}

function hashTicker(ticker: string, request: ShortTermAnalysisRequest): number {
  let value = 17;
  for (const character of `${ticker}:${request.strategyId}:${request.horizonHours}`) {
    value = (value * 31 + character.charCodeAt(0)) % 10007;
  }
  return value;
}

function rounded(value: number, digits = 2): number {
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}

export function evaluateShortTermMock(
  request: ShortTermAnalysisRequest,
): ShortTermAnalysisResult {
  const seed = hashTicker(request.ticker, request);
  const strategy = STRATEGIES[request.strategyId];
  const price = rounded(45 + (seed % 180) + (seed % 100) / 100);
  const momentum = rounded(((seed % 31) - 15) / 10, 1);
  const volatility = rounded(1.2 + (seed % 27) / 10, 1);
  const liquidity = seed % 5 === 0 ? "Thin" : seed % 3 === 0 ? "Moderate" : "Healthy";
  const catalyst = seed % 4 === 0 ? "No catalyst in fixture" : "Fixture catalyst present";
  const bullish = rounded(0.2 + (seed % 35) / 100, 2);
  const bearish = rounded(0.16 + ((seed * 7) % 28) / 100, 2);
  const neutral = rounded(1 - bullish - bearish, 2);
  const probabilities = {
    bullish,
    neutral: neutral < 0 ? 0 : neutral,
    bearish,
  };
  const highest = Math.max(probabilities.bullish, probabilities.neutral, probabilities.bearish);
  const label = probabilities.bearish === highest ? "defensive" : probabilities.bullish === highest ? "constructive" : "watch";
  const confidence = rounded(Math.min(0.91, 0.55 + (seed % 30) / 100), 2);
  const direction = momentum >= 0 ? "upward" : "downward";

  return {
    version: SHORT_TERM_LAB_VERSION,
    status: "simulated",
    request,
    strategy: { id: request.strategyId, label: strategy.label, description: strategy.description },
    marketData: {
      status: "synthetic_fixture",
      asOf: "simulated fixture",
      price: { value: price, isLive: false },
      checks: [
        {
          label: "Momentum",
          value: `${momentum >= 0 ? "+" : ""}${momentum}% / ${direction}`,
          detail: "Synthetic recent-return check; not a market quote.",
          tone: momentum >= 0 ? "positive" : "caution",
        },
        {
          label: "Volatility",
          value: `${volatility}% modeled range`,
          detail: "Synthetic volatility band for interface testing.",
          tone: volatility > 3.5 ? "caution" : "neutral",
        },
        {
          label: "Liquidity",
          value: liquidity,
          detail: "Synthetic liquidity status; no order book was queried.",
          tone: liquidity === "Thin" ? "caution" : "neutral",
        },
        {
          label: "Catalyst check",
          value: catalyst,
          detail: "No news, SEC, or provider feeds are used by this prototype.",
          tone: catalyst.startsWith("No") ? "neutral" : "caution",
        },
      ],
    },
    assessment: {
      provider: "mock-jev",
      model: MOCK_JEV_MODEL,
      label,
      confidence,
      probabilities,
      rationale: [
        `The synthetic fixture leans ${label} for the ${request.horizonHours}-hour horizon.`,
        `The ${strategy.label.toLowerCase()} profile emphasizes ${request.maxLossPct}% maximum loss tolerance.`,
        "This rationale is generated by a deterministic local mock, not Jev or a live market feed.",
      ],
    },
    evidence: [
      { label: "Synthetic price", value: `$${price.toFixed(2)}`, interpretation: "Fixture value only; not a quote." },
      { label: "Momentum check", value: `${momentum >= 0 ? "+" : ""}${momentum}%`, interpretation: "Synthetic direction signal." },
      { label: "Volatility check", value: `${volatility}%`, interpretation: "Synthetic modeled range." },
      { label: "Risk budget", value: `${request.maxLossPct}%`, interpretation: "User-entered review threshold, not an order instruction." },
    ],
    scenarios: [
      { label: "Upside", range: `+${rounded(volatility * 0.7, 1)}% to +${rounded(volatility * 1.4, 1)}%`, risk: "Trend continuation", trigger: "Synthetic momentum persists" },
      { label: "Base", range: `-${rounded(volatility * 0.25, 1)}% to +${rounded(volatility * 0.35, 1)}%`, risk: "Range-bound", trigger: "Synthetic signals remain mixed" },
      { label: "Downside", range: `-${rounded(Math.max(request.maxLossPct, volatility * 1.2), 1)}% or worse`, risk: "Invalidation", trigger: "Synthetic risk checks deteriorate" },
    ],
    limitations: [
      "All prices, probabilities, confidence values, scores, and scenarios are deterministic simulated fixtures.",
      "No live market data, news, SEC filings, broker, Jev endpoint, or trading venue was queried.",
      "A real Jev integration would require server-side authentication, request/response validation, cost controls, and calibration against labeled outcomes.",
    ],
  };
}

