import type { MarketBrief } from "@/types/market";
import { SakuraLogo } from "./SakuraLogo";
import { SectionHeader } from "./SectionHeader";
import { DemoTag } from "./ui/DemoTag";
import { EyeIcon, LeafIcon, LinkIcon, SparkleIcon } from "./ui/icons";

interface AIMarketBriefProps {
  brief: MarketBrief;
}

export function AIMarketBrief({ brief }: AIMarketBriefProps) {
  return (
    <section id="ai-brief" aria-labelledby="ai-brief-heading">
      <div className="relative overflow-hidden rounded-3xl border border-line bg-gradient-to-br from-surface via-lavender/50 to-sakura-50 p-6 shadow-card lg:p-8">
        <SakuraLogo
          size={120}
          className="pointer-events-none absolute -left-10 -top-10 opacity-[0.06]"
        />

        <SectionHeader
          id="ai-brief-heading"
          kicker="Sakura Intelligence"
          title="AI Market Brief"
          subtitle={brief.provenance}
          meta={<DemoTag label="Design preview" />}
        />

        <p className="mt-4 max-w-4xl text-sm leading-relaxed text-ink-secondary">{brief.summary}</p>

        <div className="mt-6 grid gap-6 md:grid-cols-3">
          <BriefList
            title="Key Takeaways"
            items={brief.keyTakeaways}
            icon={<LeafIcon className="h-3.5 w-3.5 text-pos" />}
          />
          <BriefList
            title="What to Watch"
            items={brief.whatToWatch}
            icon={<EyeIcon className="h-3.5 w-3.5 text-warn" />}
          />
          <BriefList
            title="Sources"
            items={brief.sources}
            icon={<LinkIcon className="h-3.5 w-3.5 text-brand" />}
            footer={`+ ${brief.sourceCount - brief.sources.length} more (demo)`}
          />
        </div>

        <p className="mt-6 flex flex-wrap items-center gap-2 border-t border-line pt-3 text-[11px] text-ink-muted">
          <SparkleIcon className="h-3.5 w-3.5 text-brand" />
          Grounded in {brief.sourceCount} sources · {brief.provenance}. Not generated by an AI model
          in Phase 0A.
        </p>
      </div>
    </section>
  );
}

interface BriefListProps {
  title: string;
  items: string[];
  icon: React.ReactNode;
  footer?: string;
}

function BriefList({ title, items, icon, footer }: BriefListProps) {
  return (
    <div>
      <h3 className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wider text-ink-secondary">
        {icon}
        {title}
      </h3>
      <ul className="mt-2.5 space-y-2">
        {items.map((item) => (
          <li key={item} className="flex gap-2 text-xs leading-relaxed text-ink-secondary">
            <span aria-hidden="true" className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-softpink" />
            <span>{item}</span>
          </li>
        ))}
      </ul>
      {footer && <p className="mt-2 text-[11px] text-ink-muted">{footer}</p>}
    </div>
  );
}
