/**
 * Nasdaq 100 constituent universe — version-controlled, static (V1.1E).
 *
 * OFFLINE SNAPSHOT — generated once by
 * `scripts/generate-nasdaq100-universe.mjs`; never scraped at runtime.
 *
 * Source: https://en.wikipedia.org/w/index.php?title=List_of_NASDAQ-100_companies&action=raw
 * Retrieval date: 2026-09-20
 * Normalization: tickers uppercased/trimmed; wiki markup stripped from names;
 * share classes kept as separate securities (the index lists 101 securities —
 * GOOGL and GOOG share one company); count is derived from this snapshot.
 * Sector: GICS sector reused from the canonical S&P 500 snapshot for symbols
 * present there (guarantees identical sector-relative anomaly math for
 * overlapping symbols); remaining symbols normalized from the source's own
 * ICB industry column via the documented ICB→GICS table in the generator.
 *
 * Known limitation: ICB industry and GICS sector are different taxonomies, so
 * 15 non-overlapping names use the normalized ICB bucket.
 *
 * Update procedure: re-run the generator, review the diff (membership, count,
 * asOf) and bump NASDAQ100_UNIVERSE_VERSION when membership changes.
 */
import type { AnomalyUniverseDefinition } from "./types";

/** Version identifier for the static constituent set (regenerate → bump). */
export const NASDAQ100_UNIVERSE_VERSION = "nasdaq100-v1";

export const nasdaq100AnomalyUniverse: AnomalyUniverseDefinition = {
  id: "nasdaq100",
  label: "Nasdaq 100",
  version: NASDAQ100_UNIVERSE_VERSION,
  asOf: "2026-09-20",
  count: 101,
  symbols: [
    "ADBE",
    "AMD",
    "ABNB",
    "ALNY",
    "GOOGL",
    "GOOG",
    "AMZN",
    "AEP",
    "AMGN",
    "ADI",
    "AAPL",
    "AMAT",
    "APP",
    "ARM",
    "ASML",
    "ALAB",
    "ADSK",
    "ADP",
    "AXON",
    "BKR",
    "BKNG",
    "AVGO",
    "CDNS",
    "CTAS",
    "CSCO",
    "CCEP",
    "CMCSA",
    "CEG",
    "CPRT",
    "CRWV",
    "COST",
    "CRWD",
    "CSX",
    "DDOG",
    "DXCM",
    "FANG",
    "DASH",
    "EXC",
    "FAST",
    "FER",
    "FTNT",
    "GEHC",
    "GILD",
    "HONA",
    "HON",
    "IDXX",
    "INTC",
    "INTU",
    "ISRG",
    "KDP",
    "KLAC",
    "LRCX",
    "LIN",
    "LITE",
    "MAR",
    "MRVL",
    "MELI",
    "META",
    "MCHP",
    "MU",
    "MSFT",
    "MSTR",
    "MDLZ",
    "MPWR",
    "MNST",
    "NBIS",
    "NFLX",
    "NVDA",
    "NXPI",
    "ORLY",
    "ODFL",
    "PCAR",
    "PLTR",
    "PANW",
    "PAYX",
    "PYPL",
    "PDD",
    "PEP",
    "QCOM",
    "REGN",
    "RKLB",
    "ROP",
    "ROST",
    "SNDK",
    "STX",
    "SHOP",
    "SPCX",
    "SBUX",
    "SNPS",
    "TMUS",
    "TTWO",
    "TER",
    "TSLA",
    "TXN",
    "TRI",
    "VRTX",
    "WMT",
    "WBD",
    "WDC",
    "WDAY",
    "XEL",
  ],
  members: [
    { ticker: "ADBE", name: "Adobe Inc.", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "AMD",
      name: "Advanced Micro Devices",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "ABNB", name: "Airbnb", sector: "Consumer Discretionary", sectorSource: "sp500" },
    { ticker: "ALNY", name: "Alnylam Pharmaceuticals", sector: "Health Care", sectorSource: "icb" },
    {
      ticker: "GOOGL",
      name: "Alphabet Inc. (Class A)",
      sector: "Communication Services",
      sectorSource: "sp500",
    },
    {
      ticker: "GOOG",
      name: "Alphabet Inc. (Class C)",
      sector: "Communication Services",
      sectorSource: "sp500",
    },
    { ticker: "AMZN", name: "Amazon", sector: "Consumer Discretionary", sectorSource: "sp500" },
    { ticker: "AEP", name: "American Electric Power", sector: "Utilities", sectorSource: "sp500" },
    { ticker: "AMGN", name: "Amgen", sector: "Health Care", sectorSource: "sp500" },
    {
      ticker: "ADI",
      name: "Analog Devices",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "AAPL", name: "Apple Inc.", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "AMAT",
      name: "Applied Materials",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "APP", name: "AppLovin", sector: "Communication Services", sectorSource: "sp500" },
    { ticker: "ARM", name: "Arm Holdings", sector: "Information Technology", sectorSource: "icb" },
    { ticker: "ASML", name: "ASML Holding", sector: "Information Technology", sectorSource: "icb" },
    { ticker: "ALAB", name: "Astera Labs", sector: "Information Technology", sectorSource: "icb" },
    { ticker: "ADSK", name: "Autodesk", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "ADP",
      name: "Automatic Data Processing",
      sector: "Industrials",
      sectorSource: "sp500",
    },
    { ticker: "AXON", name: "Axon Enterprise", sector: "Industrials", sectorSource: "sp500" },
    { ticker: "BKR", name: "Baker Hughes", sector: "Energy", sectorSource: "sp500" },
    {
      ticker: "BKNG",
      name: "Booking Holdings",
      sector: "Consumer Discretionary",
      sectorSource: "sp500",
    },
    { ticker: "AVGO", name: "Broadcom", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "CDNS",
      name: "Cadence Design Systems",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "CTAS", name: "Cintas", sector: "Industrials", sectorSource: "sp500" },
    { ticker: "CSCO", name: "Cisco", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "CCEP",
      name: "Coca-Cola Europacific Partners",
      sector: "Consumer Staples",
      sectorSource: "icb",
    },
    { ticker: "CMCSA", name: "Comcast", sector: "Communication Services", sectorSource: "sp500" },
    { ticker: "CEG", name: "Constellation Energy", sector: "Utilities", sectorSource: "sp500" },
    { ticker: "CPRT", name: "Copart", sector: "Industrials", sectorSource: "sp500" },
    { ticker: "CRWV", name: "CoreWeave", sector: "Information Technology", sectorSource: "icb" },
    { ticker: "COST", name: "Costco", sector: "Consumer Staples", sectorSource: "sp500" },
    {
      ticker: "CRWD",
      name: "CrowdStrike",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "CSX", name: "CSX Corporation", sector: "Industrials", sectorSource: "sp500" },
    { ticker: "DDOG", name: "Datadog", sector: "Information Technology", sectorSource: "sp500" },
    { ticker: "DXCM", name: "Dexcom", sector: "Health Care", sectorSource: "sp500" },
    { ticker: "FANG", name: "Diamondback Energy", sector: "Energy", sectorSource: "sp500" },
    { ticker: "DASH", name: "DoorDash", sector: "Consumer Discretionary", sectorSource: "sp500" },
    { ticker: "EXC", name: "Exelon", sector: "Utilities", sectorSource: "sp500" },
    { ticker: "FAST", name: "Fastenal", sector: "Industrials", sectorSource: "sp500" },
    { ticker: "FER", name: "Ferrovial", sector: "Industrials", sectorSource: "icb" },
    { ticker: "FTNT", name: "Fortinet", sector: "Information Technology", sectorSource: "sp500" },
    { ticker: "GEHC", name: "GE HealthCare", sector: "Health Care", sectorSource: "sp500" },
    { ticker: "GILD", name: "Gilead Sciences", sector: "Health Care", sectorSource: "sp500" },
    { ticker: "HONA", name: "Honeywell Aerospace", sector: "Industrials", sectorSource: "sp500" },
    { ticker: "HON", name: "Honeywell Technologies", sector: "Industrials", sectorSource: "sp500" },
    { ticker: "IDXX", name: "Idexx Laboratories", sector: "Health Care", sectorSource: "sp500" },
    { ticker: "INTC", name: "Intel", sector: "Information Technology", sectorSource: "sp500" },
    { ticker: "INTU", name: "Intuit", sector: "Information Technology", sectorSource: "sp500" },
    { ticker: "ISRG", name: "Intuitive Surgical", sector: "Health Care", sectorSource: "sp500" },
    { ticker: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Staples", sectorSource: "sp500" },
    {
      ticker: "KLAC",
      name: "KLA Corporation",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    {
      ticker: "LRCX",
      name: "Lam Research",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "LIN", name: "Linde plc", sector: "Materials", sectorSource: "sp500" },
    { ticker: "LITE", name: "Lumentum", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "MAR",
      name: "Marriott International",
      sector: "Consumer Discretionary",
      sectorSource: "sp500",
    },
    {
      ticker: "MRVL",
      name: "Marvell Technology",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    {
      ticker: "MELI",
      name: "Mercado Libre",
      sector: "Consumer Discretionary",
      sectorSource: "icb",
    },
    {
      ticker: "META",
      name: "Meta Platforms",
      sector: "Communication Services",
      sectorSource: "sp500",
    },
    {
      ticker: "MCHP",
      name: "Microchip Technology",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    {
      ticker: "MU",
      name: "Micron Technology",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "MSFT", name: "Microsoft", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "MSTR",
      name: "MicroStrategy",
      sector: "Information Technology",
      sectorSource: "icb",
    },
    {
      ticker: "MDLZ",
      name: "Mondelez International",
      sector: "Consumer Staples",
      sectorSource: "sp500",
    },
    {
      ticker: "MPWR",
      name: "Monolithic Power Systems",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "MNST", name: "Monster Beverage", sector: "Consumer Staples", sectorSource: "sp500" },
    { ticker: "NBIS", name: "Nebius Group", sector: "Information Technology", sectorSource: "icb" },
    { ticker: "NFLX", name: "Netflix", sector: "Communication Services", sectorSource: "sp500" },
    { ticker: "NVDA", name: "Nvidia", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "NXPI",
      name: "NXP Semiconductors",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    {
      ticker: "ORLY",
      name: "O'Reilly Automotive",
      sector: "Consumer Discretionary",
      sectorSource: "sp500",
    },
    { ticker: "ODFL", name: "Old Dominion", sector: "Industrials", sectorSource: "sp500" },
    { ticker: "PCAR", name: "Paccar", sector: "Industrials", sectorSource: "sp500" },
    {
      ticker: "PLTR",
      name: "Palantir Technologies",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    {
      ticker: "PANW",
      name: "Palo Alto Networks",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "PAYX", name: "Paychex", sector: "Industrials", sectorSource: "sp500" },
    { ticker: "PYPL", name: "PayPal", sector: "Financials", sectorSource: "sp500" },
    { ticker: "PDD", name: "PDD Holdings", sector: "Information Technology", sectorSource: "icb" },
    { ticker: "PEP", name: "PepsiCo", sector: "Consumer Staples", sectorSource: "sp500" },
    { ticker: "QCOM", name: "Qualcomm", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "REGN",
      name: "Regeneron Pharmaceuticals",
      sector: "Health Care",
      sectorSource: "sp500",
    },
    { ticker: "RKLB", name: "Rocket Lab", sector: "Industrials", sectorSource: "icb" },
    {
      ticker: "ROP",
      name: "Roper Technologies",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    {
      ticker: "ROST",
      name: "Ross Stores",
      sector: "Consumer Discretionary",
      sectorSource: "sp500",
    },
    { ticker: "SNDK", name: "Sandisk", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "STX",
      name: "Seagate Technology",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "SHOP", name: "Shopify", sector: "Information Technology", sectorSource: "icb" },
    { ticker: "SPCX", name: "SpaceX", sector: "Communication Services", sectorSource: "icb" },
    { ticker: "SBUX", name: "Starbucks", sector: "Consumer Discretionary", sectorSource: "sp500" },
    { ticker: "SNPS", name: "Synopsys", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "TMUS",
      name: "T-Mobile US",
      sector: "Communication Services",
      sectorSource: "sp500",
    },
    {
      ticker: "TTWO",
      name: "Take-Two Interactive",
      sector: "Communication Services",
      sectorSource: "sp500",
    },
    { ticker: "TER", name: "Teradyne", sector: "Information Technology", sectorSource: "sp500" },
    {
      ticker: "TSLA",
      name: "Tesla, Inc.",
      sector: "Consumer Discretionary",
      sectorSource: "sp500",
    },
    {
      ticker: "TXN",
      name: "Texas Instruments",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    {
      ticker: "TRI",
      name: "Thomson Reuters",
      sector: "Information Technology",
      sectorSource: "icb",
    },
    {
      ticker: "VRTX",
      name: "Vertex Pharmaceuticals",
      sector: "Health Care",
      sectorSource: "sp500",
    },
    { ticker: "WMT", name: "Walmart", sector: "Consumer Staples", sectorSource: "sp500" },
    {
      ticker: "WBD",
      name: "Warner Bros. Discovery",
      sector: "Communication Services",
      sectorSource: "sp500",
    },
    {
      ticker: "WDC",
      name: "Western Digital",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    {
      ticker: "WDAY",
      name: "Workday, Inc.",
      sector: "Information Technology",
      sectorSource: "sp500",
    },
    { ticker: "XEL", name: "Xcel Energy", sector: "Utilities", sectorSource: "sp500" },
  ],
  source:
    "https://en.wikipedia.org/w/index.php?title=List_of_NASDAQ-100_companies&action=raw (retrieved 2026-09-20)",
};
